server:
  port: 8006
spring:
  application:
    name: config-client
 

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka/

  instance:
    instance-id: config-8006

number: 3
